pulsar:
  service-url: pulsar://192.168.110.200:6650


logging:
  level:
    io.lesible: debug
    org.apache.pulsar.client.impl:
      ConsumerStatsRecorderImpl: off
      ProducerStatsRecorderImpl: off